drak_utilisateurs:
    resource: "@DrakUtilisateursBundle/Controller/"
    type:     annotation
    prefix:   /

drak_ecommerce:
    resource: "@DrakEcommerceBundle/Controller/"
    type:     annotation
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
