<?php

namespace Drak\EcommerceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurAdressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurAdressesRepository extends EntityRepository
{
}
